/* ============================================================
   SKILLS
   ============================================================ */
const SKILL_GROUPS = [
  { title: 'Game Development & Engines', items: ['Unity 2D/3D', 'C# / .NET', 'ECS / DOTS', 'Burst & Jobs System', 'ScriptableObjects', 'Addressables & Asset Bundles', 'Prefabs & Scene Management', 'Input System', 'URP / HDRP', 'Cinemachine', 'Unity Timeline', 'Animation Systems', 'Inverse Kinematics (IK)', 'UI (uGUI / UI Toolkit / IMGUI)', 'Physics 2D/3D', 'DoTween', 'Godot', 'GDScript'] },
  { title: 'Systems, Pipelines & Automation', items: ['CI/CD (Jenkins, GitHub Actions)', 'Build Pipelines', 'Editor Scripting & Custom Tools', 'IL2CPP / AOT / Code Stripping', 'Native Plugin Development', 'Steam SDK Integration', 'Automated & Unit Testing', 'Python & Shell Scripting', 'Internal Framework Development'] },
  { title: 'Multiplayer & Backend', items: ['Photon / Photon Fusion', 'Nakama', 'Netcode & Network Programming', 'Client-Server Architecture', 'REST APIs', 'TCP / UDP / Sockets', 'Firebase', 'Telemetry (Adjust, AppLovin, Unity Ads)', 'LiveOps'] },
  { title: 'Architecture & Engineering', items: ['Design Patterns & SOLID', 'Dependency Injection', 'Composition over Inheritance', 'Object Pooling', 'MVC / MVP', 'Multithreading & async/await', 'Serialization (JSON / XML / Protobuf / YAML)', 'Performance Profiling & Optimization', 'Memory Management'] },
  { title: 'Beyond Unity', items: ['PHP', 'JavaScript / HTML / CSS', 'TypeScript', 'SQL / MySQL', 'LAMP Stack', 'Cloud Basics (AWS / GCP / Azure)', 'Version Control (Git, Perforce, Plastic SCM)'] },
  { title: 'Ways of Working', items: ['Agile / Scrum', 'Technical Leadership & Mentoring', 'Cross-Functional Collaboration', 'Documentation', 'Rapid Prototyping'] },
];

const EXTRA_KEYWORDS = [
  'Assembly Definitions (asmdef)', 'Remote Config', 'PlayerPrefs', 'LOD', 'Navmesh & Pathfinding',
  'Finite State Machines (FSM)', 'Behaviour Trees', 'Decision Trees', 'Event-Driven Programming',
  'Reactive Programming', 'A/B Testing', 'Inversion of Control (IoC)', 'UniTask / UniRx', 'WebSockets',
  'Message Queueing', 'AWS Lambda', 'AWS Lightsail', 'WPF', 'PL/SQL', 'MariaDB', 'SQLite',
  'Asset & Content Pipelines', 'Property Drawers', 'Frame Debugger & Deep Profiling',
  'Mobile Performance Optimization', 'Legacy Code Modernization', 'Custom Logging Systems',
  'Technical Debt Reduction', 'Extraction Shooter', 'Hybrid Casual', 'Turn-Based & Real-Time Systems',
  'Graph Theory & Matrices', 'Trigonometry', 'Cross-Platform (Mobile/PC/Console)', 'Requirement Analysis',
  'Risk Assessment', 'Code Review & Git Flow', 'Package Creation', 'Video & Audio Mixer Systems',
  '3Cs (Character/Camera/Controls)', 'Project Management Tools (Trello, ClickUp, Miro, Airtable)',
];

// Synonym map so a search for how people actually phrase things ("unity3d",
// "unity game engine", "ci cd") still lights up the right pill, even when the
// pill's own display label reads differently. Built from Akhil's original,
// deliberately duplicate-heavy keyword list, plus common recruiter/hiring
// manager phrasing added on top.
const SKILL_SYNONYMS = {
  'Unity 2D/3D': ['unity', 'unity engine', 'unity game engine', 'unity 2d', 'unity 2d engine', 'unity 2d game engine', 'unity2d', 'unity 3d', 'unity 3d engine', 'unity 3d game engine', 'unity3d', 'unity dev', 'unity developer'],
  'C# / .NET': ['c#', 'c#/.net', '.net', 'csharp', 'c sharp', 'dotnet', 'dot net'],
  'ECS / DOTS': ['ecs', 'dots', 'unity dots', 'data-oriented technology stack', 'data oriented tech stack', 'entity component system'],
  'Burst & Jobs System': ['burst', 'burst compiler', 'jobs system', 'c# job system', 'job system'],
  'ScriptableObjects': ['scriptable objects', 'so pattern'],
  'Addressables & Asset Bundles': ['addressables', 'assetbundle', 'asset bundles', 'asset management'],
  'Prefabs & Scene Management': ['prefabs', 'prefab', 'scene management', 'scenes'],
  'Input System': ['unity input system', 'new input system'],
  'URP / HDRP': ['srp', 'urp', 'hdrp', 'rendering pipelines', 'universal render pipeline', 'high definition render pipeline', 'render pipeline'],
  'Cinemachine': ['cine machine'],
  'Animation Systems': ['animation', 'animations', 'animator', 'animator controllers', 'unity animation', 'animation implementation'],
  'UI (uGUI / UI Toolkit / IMGUI)': ['canvas', 'ui', 'gui', 'game ui', 'unity ui', 'ugui', 'imgui', 'ui toolkit', 'uitk', 'ui/ux', 'ui ux', 'ui development'],
  'Physics 2D/3D': ['physics', 'physics2d', 'physics3d', 'physics 2d', 'physics 3d', 'collision', 'collision2d', 'collision3d', 'physics engine'],
  'DoTween': ['dotween', 'tween', 'tweening'],
  'Godot': ['godot engine'],
  'GDScript': ['gd script', 'godot script'],
  'Unity Timeline': ['timeline', 'cutscene tool'],
  'Inverse Kinematics (IK)': ['ik', 'inverse kinematics'],
  'TypeScript': ['ts', 'type script'],
  'Object Pooling': ['object pool', 'pooling'],
  'Steam SDK Integration': ['steam sdk', 'steamworks'],
  'Message Queueing': ['message queue', 'msg queue'],
  'Property Drawers': ['property drawer'],
  'Reactive Programming': ['reactive', 'rx programming'],
  'Custom Logging Systems': ['logging system', 'custom logger'],
  '3Cs (Character/Camera/Controls)': ['3cs', 'character camera controls'],
  'Project Management Tools (Trello, ClickUp, Miro, Airtable)': ['trello', 'clickup', 'miro', 'airtable', 'project management tools'],
  'CI/CD (Jenkins, GitHub Actions)': ['devops', 'ci', 'cd', 'ci/cd', 'ci cd', 'ci/cd pipelines', 'continuous integration', 'continuous delivery', 'continuous deployment', 'build automation', 'deployment', 'jenkins', 'github actions', 'github workflows'],
  'Build Pipelines': ['build pipeline', 'build systems', 'build system', 'asset pipelines', 'content pipelines'],
  'Editor Scripting & Custom Tools': ['editor scripting', 'unity editor scripts', 'unity editor tools', 'custom editors', 'custom editor', 'tools development', 'tool development', 'developer tools', 'tooling'],
  'IL2CPP / AOT / Code Stripping': ['il2cpp', 'il2ccp', 'aot', 'code stripping', 'ahead of time compilation'],
  'Native Plugin Development': ['native plugins', 'plugin development', 'sdk integration', 'native plugin'],
  'Automated & Unit Testing': ['unit tests', 'unit testing', 'automated tests', 'automated testing', 'testing', 'qa testing', 'a/b testing', 'ab testing'],
  'Python & Shell Scripting': ['python', 'shell scripting', 'bash', 'shell script'],
  'Internal Framework Development': ['framework development', 'internal tools', 'internal framework', 'modular architecture', 'code reusability'],
  'Photon / Photon Fusion': ['photon', 'photon engine', 'fusion', 'photon fusion', 'fusion engine'],
  'Nakama': ['game server', 'game backend'],
  'Netcode & Network Programming': ['netcode', 'net code', 'networking', 'multiplayer architecture', 'network programming', 'networked gameplay'],
  'Client-Server Architecture': ['client server', 'client-server', 'server client', 'server-client'],
  'REST APIs': ['rest', 'rest api', 'restful', 'restful api', 'web requests'],
  'TCP / UDP / Sockets': ['tcp', 'udp', 'tcp/udp', 'sockets', 'socket programming', 'websocket', 'websocket programming'],
  'Firebase': [],
  'Telemetry (Adjust, AppLovin, Unity Ads)': ['adjust', 'applovin', 'ad lovin', 'unity ads', 'telemetry', 'data collection', 'ad mediation'],
  'LiveOps': ['live ops', 'live operations', 'live game', 'production support'],
  'Design Patterns & SOLID': ['design patterns', 'oop design patterns', 'oop', 'object oriented programming', 'software design patterns', 'architectural patterns', 'solid', 'solid principles', 'solid design principles'],
  'Dependency Injection': ['di', 'dependency injection (di)', 'dependency management', 'inversion of control', 'ioc'],
  'Composition over Inheritance': ['composition', 'component-based architecture', 'component based architecture'],
  'MVC / MVP': ['mvc', 'mvp', 'mvvm'],
  'Multithreading & async/await': ['multithreading', 'multi-threading', 'multi threading', 'c# tasks', '.net tasks', 'tasks', 'async/await', 'async await', 'asynchronous programming'],
  'Serialization (JSON / XML / Protobuf / YAML)': ['serialization', 'protobuf', 'json', 'xml', 'yaml', 'file handling', 'i/o', 'io operations'],
  'Performance Profiling & Optimization': ['optimization', 'performance optimization', 'bottleneck identification', 'mobile performance optimization', 'memory management optimization', 'runtime performance optimization', 'mobile optimization', 'runtime optimization', 'performance engineering', 'unity profiler', 'cpu profiling', 'gpu profiling', 'memory profiling', 'frame debugger', 'deep profiling', 'profiling', 'frame rate optimization', 'reducing load times'],
  'Memory Management': ['memory optimization', 'memory leaks', 'garbage collection'],
  'PHP': [],
  'JavaScript / HTML / CSS': ['javascript', 'js', 'html', 'css', 'jquery'],
  'SQL / MySQL': ['sql', 'databases', 'mysql'],
  'LAMP Stack': ['lamp', 'backend', 'server-side', 'server side'],
  'Cloud Basics (AWS / GCP / Azure)': ['cloud', 'azure', 'gcp', 'aws', 'aws lambda', 'aws lightsail', 'cloud computing'],
  'Version Control (Git, Perforce, Plastic SCM)': ['version control', 'git', 'plastic scm', 'perforce', 'perforce p4', 'source control'],
  'Agile / Scrum': ['agile', 'scrum', 'agile development', 'sprint planning', 'scrum master'],
  'Technical Leadership & Mentoring': ['technical leadership', 'leadership', 'mentoring', 'mentorship', 'tech lead'],
  'Cross-Functional Collaboration': ['collaboration', 'cross-functional', 'cross functional', 'remote collaboration', 'distributed teams'],
  'Documentation': ['technical design documentation', 'technical documentation', 'reporting and documentation'],
  'Rapid Prototyping': ['prototyping', 'prototype'],
  'Assembly Definitions (asmdef)': ['assembly', 'assemblies', 'assembly definition', 'asmdef'],
  'Remote Config': [],
  'PlayerPrefs': ['player prefs'],
  'LOD': ['level of detail'],
  'Navmesh & Pathfinding': ['navmesh', 'pathfinding', 'navigation mesh', 'nav mesh'],
  'Finite State Machines (FSM)': ['fsm', 'state machine', 'finite state machine'],
  'Behaviour Trees': ['behavior tree', 'behavior trees', 'behaviour tree'],
  'Decision Trees': ['decision tree'],
  'Event-Driven Programming': ['event driven', 'event-driven', 'observer pattern', 'pub sub'],
  'A/B Testing': ['ab testing'],
  'Inversion of Control (IoC)': ['ioc', 'inversion of control'],
  'UniTask / UniRx': ['unitask', 'unirx', 'uni task', 'uni rx'],
  'WebSockets': ['websocket'],
  'AWS Lambda': [],
  'AWS Lightsail': [],
  'WPF': [],
  'PL/SQL': ['plsql'],
  'MariaDB': [],
  'SQLite': ['sqlite3'],
  'Asset & Content Pipelines': ['asset pipeline', 'content pipeline', 'asset integration'],
  'Frame Debugger & Deep Profiling': ['frame debugger', 'deep profiling'],
  'Mobile Performance Optimization': ['mobile optimization'],
  'Legacy Code Modernization': ['legacy code'],
  'Technical Debt Reduction': ['tech debt', 'technical debt'],
  'Extraction Shooter': ['extraction fps'],
  'Hybrid Casual': ['hybrid-casual', 'mid-core', 'midcore'],
  'Turn-Based & Real-Time Systems': ['real-time', 'realtime', 'real time', 'turn-based', 'turn based'],
  'Graph Theory & Matrices': ['matrix', 'graph theory', 'sets', 'set theory', 'algebra'],
  'Trigonometry': ['trig'],
  'Cross-Platform (Mobile/PC/Console)': ['multi platform', 'multi-platform development', 'platform deployment', 'cross platform', 'cross-platform', 'cross platform development', 'multiplatform'],
  'Requirement Analysis': ['requirements gathering', 'analysis'],
  'Risk Assessment': ['technical risk assessment', 'risk management'],
  'Code Review & Git Flow': ['code review', 'git flow', 'code quality', 'pull request review'],
  'Package Creation': ['unity package'],
  'Video & Audio Mixer Systems': ['video', 'audio', 'audio mixer', 'audio systems', 'sound design'],
};
